site_name: Panoptic Docs
theme:
  name: material
  logo: assets/logo_panoptic_grand.png
  favicon: assets/logo_panoptic_petit.png
  icon:
    repo: fontawesome/brands/github
  palette: 

  # Palette toggle for light mode
  - scheme: default
    media: "(prefers-color-scheme: light)"
    primary: purple
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    media: "(prefers-color-scheme: dark)"
    primary: purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
# - announce.dismiss
  # - content.action.edit
  # - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.tooltips
  # - header.autohide
  # - navigation.expand
  - navigation.indexes
  # - navigation.instant
  # - navigation.prune
  - navigation.sections
  - navigation.tabs
  # - navigation.tabs.sticky
  # - navigation.top
  - navigation.footer
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  # - toc.integrate
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/CERES-Sorbonne/Panoptic
repo_name: Panoptic
nav:
  - Accueil: index.md
  - Installation: 
    - Installation Standard: install/install.md
    - Installation Standard - Outils de Similarité: install/install_plugin.md
    - Installation Developpeurs: install/install_dev.md
  - Utilisation:
    - Premier Lancement: start/first_start.md
    - Créer un projet: start/projets.md
    - Importer des Images: start/images.md
    - Les Propriétés: start/properties.md
    - Annoter les Propriétés: start/annotate.md
    - Importer des Propriétés: start/propsimport.md
    - Exporter des Propriétés: start/propsexport.md
    - Manipuler les Images à partir de leurs Propriétés: start/filters.md
    - La Similarité:
      - Les Clusters: start/clusters.md
      - Les Images Similaires: start/similar.md
      - Les Recommandations: start/reco.md
      - La Similarité Textuelle: start/text.md
  - Approfondir:
    - Comprendre l'import des images: advanced/import.md
    - Comprendre les instances: advanced/instances.md
    - Projets: 
      - Partager un projet: advanced/projectimport.md
      - Paramétrer un projet: advanced/projectparams.md
    - Gérer ses tags:
      - Types de tags: advanced/tags.md
      - Modal des tags: advanced/tagsmodal.md
    - Les onglets: advanced/onglets.md
    - Astuces et raccourcis: advanced/astuces.md
    - Choisir son modèle: advances/models.md
  - Plugins:
    - Introduction: plugins/intro.md
    - Ajouter des plugins: plugins/add.md
    - Créer ses plugins: plugins/create.md
  - Méthodologies proposées:
    - Créer des clusters pour identifier des tendances: method/clusters.md
    - Identifier des doublons: method/duplicates.md
    - Débruiter son corpus: method/noise.md
    - Gérer ses espaces de travail: method/workspaces.md
  - Cas d'Usage: 
    - Images d'archive: usecases/bnf.md
    - Instagram: usecases/insta.md
    - Memes: usecases/memes.md
    - Films: usecases/movies.md
  - Glossaire: concepts.md
  - FAQ: faq.md
  - Ressources Utiles: resources.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true