site_name: Panoptic Docs
theme:
  name: material
  logo: assets/logo_panoptic_grand.png
  favicon: assets/logo_panoptic_petit.png
  icon:
    repo: fontawesome/brands/github
  palette: 
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/CERES-Sorbonne/Panoptic
repo_name: Panoptic

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Accueil: Home
            Installation: Installation
            'Installation Standard': 'Standard Installation'
            'Installation Standard - Outils de Similarité': 'Standard Installation - Similarity Tools'
            'Installation Developpeurs': 'Developer Installation'
            Utilisation: Usage
            'Premier Lancement': 'First Start'
            'Créer un projet': 'Create a project'
            'Importer des Images': 'Import Images'
            'Les Propriétés': 'Properties'
            'Annoter les Propriétés': 'Annotate Properties'
            'Importer des Propriétés': 'Import Properties'
            'Exporter des Propriétés': 'Export Properties'
            'Manipuler les Images à partir de leurs Propriétés': 'Manipulate Images from their Properties'
            'La Similarité': 'Similarity'
            'Les Clusters': 'Clusters'
            'Les Images Similaires': 'Similar Images'
            'Les Recommandations': 'Recommendations'
            'La Similarité Textuelle': 'Text Similarity'
            Approfondir: Advanced
            "Comprendre l'import des images": "Understanding image import"
            "Comprendre les instances": "Understanding instances"
            Projets: Projects
            "Partager un projet": "Share a project"
            "Paramétrer un projet": "Set up a project"
            "Gérer ses tags": "Manage tags"
            "Types de tags": "Tag types"
            "Modal des tags": "Tags modal"
            "Les onglets": "Tabs"
            "Astuces et raccourcis": "Tips and shortcuts"
            "Choisir son modèle": "Choose your model"
            Plugins: Plugins
            Introduction: Introduction
            "Ajouter des plugins": "Add plugins"
            "Créer ses plugins": "Create plugins"
            'Méthodologies proposées': Methodologies
            "Créer des clusters pour identifier des tendances": "Create clusters to identify trends"
            "Identifier des doublons": "Identify duplicates"
            "Débruiter son corpus": "Clean your corpus"
            "Gérer ses espaces de travail": "Manage your workspaces"
            "Cas d'Usage": "Use Cases"
            "Images d'archive": "Archive images"
            Instagram: Instagram
            Memes: Memes
            Films: Movies
            Glossaire: Glossary
            FAQ: FAQ
            'Ressources Utiles': Resources

nav:
  - Accueil: index.md
  - Installation: 
    - Installation Standard: install/install.md
    - Installation Standard - Outils de Similarité: install/install_plugin.md
    - Installation Developpeurs: install/install_dev.md
  - Utilisation:
    - Premier Lancement: start/first_start.md
    - Créer un projet: start/projets.md
    - Importer des Images: start/images.md
    - Les Propriétés: start/properties.md
    - Annoter les Propriétés: start/annotate.md
    - Importer des Propriétés: start/propsimport.md
    - Importer des Tags / Thésaurus: start/tagsimport.md
    - Exporter des Propriétés: start/propsexport.md
    - Manipuler les Images à partir de leurs Propriétés: start/filters.md
    - La Similarité:
      - Les Clusters: start/clusters.md
      - Les Images Similaires: start/similar.md
      - Les Recommandations: start/reco.md
      - La Similarité Textuelle: start/text.md
  - Approfondir:
    - Comprendre l'import des images: advanced/import.md
    - Comprendre les instances: advanced/instances.md
    - Projets: 
      - Partager un projet: advanced/projectimport.md
      - Paramétrer un projet: advanced/projectparams.md
    - Gérer ses tags:
      - Types de tags: advanced/tags.md
      - Modal des tags: advanced/tagsmodal.md
    - Les onglets: advanced/onglets.md
    - Astuces et raccourcis: advanced/astuces.md
    - Choisir son modèle: advanced/models.md
  - Plugins:
    - Introduction: plugins/intro.md
    - Ajouter des plugins: plugins/add.md
    - Créer ses plugins: plugins/dev.md
  - Méthodologies proposées:
    - Introduction: method/intro.md
    - Créer des clusters pour identifier des tendances: method/clusters.md
    - Identifier des doublons: method/duplicates.md
    - Débruiter son corpus: method/noise.md
    - Gérer ses espaces de travail: method/workspaces.md
  - Cas d'Usage: 
    - Images d'archive: usecases/bnf.md
    - Instagram: usecases/insta.md
    - Memes: usecases/memes.md
    - Films: usecases/movies.md
  - Glossaire: concepts.md
  - FAQ: faq.md
  - Ressources Utiles: resources.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true